apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: DB
    project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
      tier: DB
      project: roboshop
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
        tier: DB
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: parasuramkoppada/mongodb:k8
